title: Neural Nets Adventures
description: Convolutional Nets, LSTM, Reinforcement Learning
#url: "https://josehoras.github.io/"
url: "Jose Horas"
#permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
