# Site settings
title: Jose Horas blog
description: Notes on Neural Nets
url: "https://josehoras.github.io/"
author:
  name: "Jose Horas"
  email: "jose.horas@gmail.com"
  url: "https://josehoras.github.io/"

# Build settings
baseurl: "/"
markdown: kramdown
source: .
destination: ./_site
permalink: /:title/
paginate: 10
paginate_path: /page:num/
tag_page_dir: "tag"

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
