title: Jose Horas blog
description: Notes on Neural Nets
#excerpt: "Why I decided to blog in Jekyll on GitHub instead of WordPress."
url: "https://josehoras.github.io/"
#url: "Jose Horas"
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
